# Configuration file for ConstructionWands plugin
# Define custom construction wands and messages
# Each wand has specific attributes like name, model data, 
# range, length, delay, source hand, type, uses, and whether it is infinite.
# Source: inventory | offhand
# Modify the values as needed to customize your wands.
# Wands can be given to players using the /wand command defined in plugin.yml
# Ensure that the permissions are set correctly in plugin.yml to control access to the commands.
# Example wands are provided below.

# Language setting - Available: en_US, it_IT
# Messages are defined in lang.yml
lang: it_IT

# Blocked blocks - blocks on which wands cannot place blocks
# Add any Minecraft material name to prevent placement on those blocks
blocked-blocks:
  - SPAWNER
  - BEDROCK
  - BARRIER
  - COMMAND_BLOCK
  - CHAIN_COMMAND_BLOCK
  - REPEATING_COMMAND_BLOCK
  - STRUCTURE_BLOCK
  - JIGSAW
  - END_PORTAL_FRAME
  - CHEST
  - TRAPPED_CHEST
  - BARREL
  - FURNACE
  - DISPENSER
  - DROPPER
  - HOPPER
  - ANVIL
  - ENDER_CHEST

# Undo timeout in milliseconds (60000 = 60 seconds)
undo-timeout: 60000
